/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface CrowdfundingPlatformInterface extends utils.Interface {
  functions: {
    "campaignCounter()": FunctionFragment;
    "campaigns(uint256)": FunctionFragment;
    "contribute(uint256)": FunctionFragment;
    "createCampaign(string,string,string,uint256,uint256)": FunctionFragment;
    "createMilestone(uint256,string,uint256,uint256)": FunctionFragment;
    "enablePremiumFeatures(uint256)": FunctionFragment;
    "getCampaignDetails(uint256)": FunctionFragment;
    "getMilestone(uint256,uint256)": FunctionFragment;
    "getUserContribution(uint256,address)": FunctionFragment;
    "owner()": FunctionFragment;
    "platformFeePercent()": FunctionFragment;
    "releaseMilestoneFunds(uint256,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requestRefund(uint256)": FunctionFragment;
    "setPlatformFee(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "userCampaigns(address,uint256)": FunctionFragment;
    "userContributions(address,uint256)": FunctionFragment;
    "voteOnMilestone(uint256,uint256,bool)": FunctionFragment;
    "withdrawPlatformFunds()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "campaignCounter"
      | "campaigns"
      | "contribute"
      | "createCampaign"
      | "createMilestone"
      | "enablePremiumFeatures"
      | "getCampaignDetails"
      | "getMilestone"
      | "getUserContribution"
      | "owner"
      | "platformFeePercent"
      | "releaseMilestoneFunds"
      | "renounceOwnership"
      | "requestRefund"
      | "setPlatformFee"
      | "transferOwnership"
      | "userCampaigns"
      | "userContributions"
      | "voteOnMilestone"
      | "withdrawPlatformFunds"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "campaignCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createMilestone",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "enablePremiumFeatures",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignDetails",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestone",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserContribution",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseMilestoneFunds",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRefund",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "userCampaigns",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "userContributions",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnMilestone",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "campaignCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enablePremiumFeatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestoneFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteOnMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFunds",
    data: BytesLike
  ): Result;

  events: {
    "CampaignCreated(uint256,address,string,uint256)": EventFragment;
    "ContributionMade(uint256,address,uint256)": EventFragment;
    "FundsReleased(uint256,uint256,uint256)": EventFragment;
    "MilestoneCreated(uint256,uint256,string,uint256)": EventFragment;
    "MilestoneVoted(uint256,uint256,address,bool)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PremiumActivated(uint256)": EventFragment;
    "RefundIssued(uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CampaignCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContributionMade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundsReleased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MilestoneCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MilestoneVoted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PremiumActivated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RefundIssued"): EventFragment;
}

export interface CampaignCreatedEventObject {
  campaignId: BigNumber;
  creator: string;
  title: string;
  goalAmount: BigNumber;
}
export type CampaignCreatedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber],
  CampaignCreatedEventObject
>;

export type CampaignCreatedEventFilter = TypedEventFilter<CampaignCreatedEvent>;

export interface ContributionMadeEventObject {
  campaignId: BigNumber;
  contributor: string;
  amount: BigNumber;
}
export type ContributionMadeEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  ContributionMadeEventObject
>;

export type ContributionMadeEventFilter =
  TypedEventFilter<ContributionMadeEvent>;

export interface FundsReleasedEventObject {
  campaignId: BigNumber;
  milestoneId: BigNumber;
  amount: BigNumber;
}
export type FundsReleasedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  FundsReleasedEventObject
>;

export type FundsReleasedEventFilter = TypedEventFilter<FundsReleasedEvent>;

export interface MilestoneCreatedEventObject {
  campaignId: BigNumber;
  milestoneId: BigNumber;
  description: string;
  amount: BigNumber;
}
export type MilestoneCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber],
  MilestoneCreatedEventObject
>;

export type MilestoneCreatedEventFilter =
  TypedEventFilter<MilestoneCreatedEvent>;

export interface MilestoneVotedEventObject {
  campaignId: BigNumber;
  milestoneId: BigNumber;
  voter: string;
  vote: boolean;
}
export type MilestoneVotedEvent = TypedEvent<
  [BigNumber, BigNumber, string, boolean],
  MilestoneVotedEventObject
>;

export type MilestoneVotedEventFilter = TypedEventFilter<MilestoneVotedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PremiumActivatedEventObject {
  campaignId: BigNumber;
}
export type PremiumActivatedEvent = TypedEvent<
  [BigNumber],
  PremiumActivatedEventObject
>;

export type PremiumActivatedEventFilter =
  TypedEventFilter<PremiumActivatedEvent>;

export interface RefundIssuedEventObject {
  campaignId: BigNumber;
  contributor: string;
  amount: BigNumber;
}
export type RefundIssuedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  RefundIssuedEventObject
>;

export type RefundIssuedEventFilter = TypedEventFilter<RefundIssuedEvent>;

export interface CrowdfundingPlatform extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CrowdfundingPlatformInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    campaignCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        boolean,
        BigNumber
      ] & {
        id: BigNumber;
        creator: string;
        title: string;
        description: string;
        imageUrl: string;
        goalAmount: BigNumber;
        raisedAmount: BigNumber;
        deadline: BigNumber;
        status: number;
        isPremium: boolean;
        milestoneCount: BigNumber;
      }
    >;

    contribute(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createCampaign(
      _title: PromiseOrValue<string>,
      _description: PromiseOrValue<string>,
      _imageUrl: PromiseOrValue<string>,
      _goalAmount: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _description: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    enablePremiumFeatures(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getCampaignDetails(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        boolean,
        BigNumber
      ] & {
        id: BigNumber;
        creator: string;
        title: string;
        description: string;
        imageUrl: string;
        goalAmount: BigNumber;
        raisedAmount: BigNumber;
        deadline: BigNumber;
        status: number;
        isPremium: boolean;
        contributorCount: BigNumber;
      }
    >;

    getMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, number, BigNumber, BigNumber] & {
        description: string;
        amount: BigNumber;
        deadline: BigNumber;
        status: number;
        votesFor: BigNumber;
        votesAgainst: BigNumber;
      }
    >;

    getUserContribution(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    platformFeePercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    releaseMilestoneFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requestRefund(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPlatformFee(
      _newFeePercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    userCampaigns(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    userContributions(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    voteOnMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      _vote: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawPlatformFunds(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  campaignCounter(overrides?: CallOverrides): Promise<BigNumber>;

  campaigns(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      number,
      boolean,
      BigNumber
    ] & {
      id: BigNumber;
      creator: string;
      title: string;
      description: string;
      imageUrl: string;
      goalAmount: BigNumber;
      raisedAmount: BigNumber;
      deadline: BigNumber;
      status: number;
      isPremium: boolean;
      milestoneCount: BigNumber;
    }
  >;

  contribute(
    _campaignId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createCampaign(
    _title: PromiseOrValue<string>,
    _description: PromiseOrValue<string>,
    _imageUrl: PromiseOrValue<string>,
    _goalAmount: PromiseOrValue<BigNumberish>,
    _deadline: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createMilestone(
    _campaignId: PromiseOrValue<BigNumberish>,
    _description: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _deadline: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  enablePremiumFeatures(
    _campaignId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getCampaignDetails(
    _campaignId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      number,
      boolean,
      BigNumber
    ] & {
      id: BigNumber;
      creator: string;
      title: string;
      description: string;
      imageUrl: string;
      goalAmount: BigNumber;
      raisedAmount: BigNumber;
      deadline: BigNumber;
      status: number;
      isPremium: boolean;
      contributorCount: BigNumber;
    }
  >;

  getMilestone(
    _campaignId: PromiseOrValue<BigNumberish>,
    _milestoneId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, number, BigNumber, BigNumber] & {
      description: string;
      amount: BigNumber;
      deadline: BigNumber;
      status: number;
      votesFor: BigNumber;
      votesAgainst: BigNumber;
    }
  >;

  getUserContribution(
    _campaignId: PromiseOrValue<BigNumberish>,
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  platformFeePercent(overrides?: CallOverrides): Promise<BigNumber>;

  releaseMilestoneFunds(
    _campaignId: PromiseOrValue<BigNumberish>,
    _milestoneId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requestRefund(
    _campaignId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPlatformFee(
    _newFeePercent: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  userCampaigns(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  userContributions(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  voteOnMilestone(
    _campaignId: PromiseOrValue<BigNumberish>,
    _milestoneId: PromiseOrValue<BigNumberish>,
    _vote: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawPlatformFunds(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    campaignCounter(overrides?: CallOverrides): Promise<BigNumber>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        boolean,
        BigNumber
      ] & {
        id: BigNumber;
        creator: string;
        title: string;
        description: string;
        imageUrl: string;
        goalAmount: BigNumber;
        raisedAmount: BigNumber;
        deadline: BigNumber;
        status: number;
        isPremium: boolean;
        milestoneCount: BigNumber;
      }
    >;

    contribute(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createCampaign(
      _title: PromiseOrValue<string>,
      _description: PromiseOrValue<string>,
      _imageUrl: PromiseOrValue<string>,
      _goalAmount: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _description: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    enablePremiumFeatures(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getCampaignDetails(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        boolean,
        BigNumber
      ] & {
        id: BigNumber;
        creator: string;
        title: string;
        description: string;
        imageUrl: string;
        goalAmount: BigNumber;
        raisedAmount: BigNumber;
        deadline: BigNumber;
        status: number;
        isPremium: boolean;
        contributorCount: BigNumber;
      }
    >;

    getMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, number, BigNumber, BigNumber] & {
        description: string;
        amount: BigNumber;
        deadline: BigNumber;
        status: number;
        votesFor: BigNumber;
        votesAgainst: BigNumber;
      }
    >;

    getUserContribution(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    platformFeePercent(overrides?: CallOverrides): Promise<BigNumber>;

    releaseMilestoneFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requestRefund(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPlatformFee(
      _newFeePercent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    userCampaigns(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userContributions(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    voteOnMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      _vote: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawPlatformFunds(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "CampaignCreated(uint256,address,string,uint256)"(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      creator?: PromiseOrValue<string> | null,
      title?: null,
      goalAmount?: null
    ): CampaignCreatedEventFilter;
    CampaignCreated(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      creator?: PromiseOrValue<string> | null,
      title?: null,
      goalAmount?: null
    ): CampaignCreatedEventFilter;

    "ContributionMade(uint256,address,uint256)"(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      contributor?: PromiseOrValue<string> | null,
      amount?: null
    ): ContributionMadeEventFilter;
    ContributionMade(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      contributor?: PromiseOrValue<string> | null,
      amount?: null
    ): ContributionMadeEventFilter;

    "FundsReleased(uint256,uint256,uint256)"(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      milestoneId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): FundsReleasedEventFilter;
    FundsReleased(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      milestoneId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): FundsReleasedEventFilter;

    "MilestoneCreated(uint256,uint256,string,uint256)"(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      milestoneId?: PromiseOrValue<BigNumberish> | null,
      description?: null,
      amount?: null
    ): MilestoneCreatedEventFilter;
    MilestoneCreated(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      milestoneId?: PromiseOrValue<BigNumberish> | null,
      description?: null,
      amount?: null
    ): MilestoneCreatedEventFilter;

    "MilestoneVoted(uint256,uint256,address,bool)"(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      milestoneId?: PromiseOrValue<BigNumberish> | null,
      voter?: PromiseOrValue<string> | null,
      vote?: null
    ): MilestoneVotedEventFilter;
    MilestoneVoted(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      milestoneId?: PromiseOrValue<BigNumberish> | null,
      voter?: PromiseOrValue<string> | null,
      vote?: null
    ): MilestoneVotedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "PremiumActivated(uint256)"(
      campaignId?: PromiseOrValue<BigNumberish> | null
    ): PremiumActivatedEventFilter;
    PremiumActivated(
      campaignId?: PromiseOrValue<BigNumberish> | null
    ): PremiumActivatedEventFilter;

    "RefundIssued(uint256,address,uint256)"(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      contributor?: PromiseOrValue<string> | null,
      amount?: null
    ): RefundIssuedEventFilter;
    RefundIssued(
      campaignId?: PromiseOrValue<BigNumberish> | null,
      contributor?: PromiseOrValue<string> | null,
      amount?: null
    ): RefundIssuedEventFilter;
  };

  estimateGas: {
    campaignCounter(overrides?: CallOverrides): Promise<BigNumber>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contribute(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createCampaign(
      _title: PromiseOrValue<string>,
      _description: PromiseOrValue<string>,
      _imageUrl: PromiseOrValue<string>,
      _goalAmount: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _description: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    enablePremiumFeatures(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getCampaignDetails(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserContribution(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    platformFeePercent(overrides?: CallOverrides): Promise<BigNumber>;

    releaseMilestoneFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requestRefund(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPlatformFee(
      _newFeePercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    userCampaigns(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userContributions(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    voteOnMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      _vote: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawPlatformFunds(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    campaignCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    campaigns(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contribute(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createCampaign(
      _title: PromiseOrValue<string>,
      _description: PromiseOrValue<string>,
      _imageUrl: PromiseOrValue<string>,
      _goalAmount: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _description: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    enablePremiumFeatures(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getCampaignDetails(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserContribution(
      _campaignId: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    platformFeePercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    releaseMilestoneFunds(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requestRefund(
      _campaignId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPlatformFee(
      _newFeePercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    userCampaigns(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userContributions(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    voteOnMilestone(
      _campaignId: PromiseOrValue<BigNumberish>,
      _milestoneId: PromiseOrValue<BigNumberish>,
      _vote: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawPlatformFunds(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
