#!/bin/bash

# Sepolia Setup Helper Script
# Opens faucets and displays your testnet wallet

ADDRESS="0x8b3dfD81484530B484964fdFBD490530edE324e3"
PRIVATE_KEY="0x26f7d4e301245338855266999abfa9f4cb2b4f2f64490f01a40f3579d3ae636f"

echo "CrowdChain Sepolia Setup"
echo "=================================="
echo ""
echo "Your Sepolia Testnet Wallet:"
echo "Address: $ADDRESS"
echo ""
echo "⚠️  Keep your private key SECRET!"
echo ""
echo "📍 Check your balance:"
echo "https://sepolia.etherscan.io/address/$ADDRESS"
echo ""
echo "💧 Request test ETH from faucets:"
echo ""
echo "1️⃣  FASTEST - Alchemy Sepolia Faucet (0.5 ETH, 1-2 min):"
echo "   https://sepoliafaucet.com"
echo ""
echo "2️⃣  QuickNode Faucet (0.1 ETH, 2-5 min):"
echo "   https://faucet.quicknode.com/ethereum/sepolia"
echo ""
echo "3️⃣  Infura Faucet (varies):"
echo "   https://www.infura.io/faucet/sepolia"
echo ""
echo "📝 Steps:"
echo "  1. Open one of the faucet links above"
echo "  2. Paste your address: $ADDRESS"
echo "  3. Request ETH and wait"
echo "  4. Check balance with the Etherscan link above"
echo "  5. Once you have ETH, run:"
echo "     npx hardhat run scripts/deploy.js --network sepolia"
echo ""
echo "=================================="
